### ISSUE TITLE
Check the photos of all resistors and capacitors

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKotec-Website#14]
resistors: https://askotec.openculture.agency/?s=Resistors&post_type=product

capacitors: https://askotec.openculture.agency/?s=Capacitors&post_type=product

**Comment by timmwille** [comment]
Capacitors: Blue is 100µF and black 10µF → switch

**Comment by timmwille** [comment]
100Ohm is wrong picture of Diodes please change
https://askotec.openculture.agency/product/resistors-100-%cf%89/

**Comment by timmwille** [comment]
Here link to Diodes
https://www.segor.de/#Q=1N4007&M=1

**Comment by timmwille** [comment]
done now only #48 missing, this part is closed
