### ISSUE TITLE
Create Open Documentation Guide in Stockroom

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKotec-Website#34]
- [x] create product
- [x] add price (0€?)
- [x] add supplier (r0g?)
- [x] add Description 
- [x] add Picture(s)
- [x] Link [Repo](https://github.com/opencultureagency/Open-Documentation-Guide)

**Comment by timmwille** [comment]
I think actually the Open Learning Guide has pictures of the Open Documentation Guide
https://askotec.openculture.agency/product/open-learning-guide/ @nour93-02

**Comment by nour93-02** [comment]
Yea I just checked, I will change it. Thanks Timm.
