### ISSUE TITLE
Add mobile repair kit bit adapters to Stockroom

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKotec-Website#40]
this set of bit adapters is needed to also be able to repair laptops with bigger torx screws

**Comment by timmwille** [comment]
worst case this one:
https://www.reichelt.de/bit-satz-10-teilig-torx-tx--donau-mbs67-p114908.html as alternative

**Comment by timmwille** [comment]
this set has probably all sizes one needs, as reference:
https://www.reichelt.de/ifixit-essential-electronics-toolkit-v2-if-145-348-2-p257612.html

not sure which size was missing in the mobile repair kit

**Comment by bmen** [comment]
Teba1 | Torx Bits (T7, T8, T9) | T3 T4 T5 T6 T7 T8 T9 T10 T15 T20 28mm | T | 1,89 |   | ebay |   | https://www.ebay.de/itm/10Stk-CR-V-Torx-Bits-Biteinsatz-Bit-T3-T4-T5-T6-T7-T8-T9-T10-T15-T20-TX-Bits/193255538457?hash=item2cfeed7f19:g:0bcAAOSwBrRd88Rr

**Comment by bmen** [comment]
only missing picture: #44
