### ISSUE TITLE
Add Headlamp to Demo case and update stockroom

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKotec-Website#41]
I think this one is still missing, I will also add another issue to Bug-Fix the Main branch as this is an item in each #ASKotec 2.0

**Comment by bmen** [comment]
TSta1 | Headlamp | Arcas 3W LED, 120 lumen | T | 9,99 | 

* https://www.reichelt.com/de/de/led-stirnleuchte-80-lm-weiss-grau-3x-aaa-micro-ans-1600-0077-p214541.html
* https://www.reichelt.com/de/de/led-taschenlampe-power-line-1-w-100-lm-schwarz-3x-aaa-var-led-ihl-p203350.html

**Comment by bmen** [comment]
https://askotec.openculture.agency/product/led-headlight/
