### ISSUE TITLE
Supplier research for capacitors and resistors

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKotec-Website#5]
https://askotec.openculture.agency/?s=Capacitors&post_type=product

https://askotec.openculture.agency/?s=resistors&post_type=product

**Comment by timmwille** [comment]
https://www.segor.de/#Q=ELRA100u-35%252F105%25C2%25B0&M=1

100 ̣µF

(kann zukünftig auch 20x selber Typ sein) noch in v2.0 10x

**Comment by timmwille** [comment]
@bmen

**Comment by timmwille** [comment]
10µF 10x

https://www.segor.de/#Q=ELRA10u-35%252F105%25C2%25B0%252F4x7&M=1

**Comment by timmwille** [comment]
100Ohm Suplier 2
https://www.reichelt.de/widerstand-metallschicht-100-ohm-0207-0-6-w-1--metall-100-p11457.html?&trstct=pos_0&nbc=1

**Comment by timmwille** [comment]
Resistors:
https://www.reichelt.de/metallschichtwiderstaende-c8379.html?&nbc=1

**Comment by timmwille** [comment]
Segor 1kOhm
https://www.segor.de/#Q=MF1k0-1%2525&M=1

Segor 100Ohm
https://www.segor.de/#Q=MF100R-1%2525&M=1

300Ohm
https://www.segor.de/#Q=MF300R-1%2525&M=1

Segor 10 Ohm
https://www.segor.de/#Q=MF10R-1%2525&M=1

15Ohm
https://www.segor.de/#Q=MF15R-1%2525&M=1

**Comment by timmwille** [comment]
done
