### ISSUE TITLE
Do we need Bread Board Small Protoboard Size 170 as single product?

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKotec-Website#7]
It''s not included in the arduino kit?

i founded it as single product in the content list.

**Comment by timmwille** [comment]
damn, yes it is missing 4times included inside one of the orange containers actually to be exact

As you can see here:
https://raw.githubusercontent.com/opencultureagency/ASKotec/master/thumbs/thumb-2.jpg

Actually the picture in the Stockroom for the ASKmod in this case is missing one and the 400 one is linked but this one goes into the Arduino Set and the 170 goes 4x into the assortment box :=) 
https://askotec.openculture.agency/product/askmod-electronics-assortment-set/

**Comment by bmen** [comment]
Only the image is missing -> see: #57
